routes/web.php
<?php

Auth::routes();
Route::get('/', 'HomeController@index');

Route::group(['middleware' => ['auth']], function () {

    Route::get('/dashboard', 'HomeController@index')->name('dashboard');

    Route::prefix('roles')->group(function () {
        Route::resource('/menu', 'Roles\MenuController');
        Route::get('/menu/menuControllerChangeStatus/{id}', 'Roles\MenuController@changeStatus');
        Route::resource('/group', 'Roles\UserGroupController');
        Route::get('/roleAccessIndex', 'Roles\RoleAccessController@index');
        Route::get('roleChangeAccess/{allowId}/{id}', 'Roles\RoleAccessController@changeAccess');
    });

    Route::resource('/user', 'UserController');
    Route::get('/user/status/{id}', 'UserController@status');
    Route::get('/profile', 'UserController@profile')->name('profile');
    Route::post('profile/profilePic', 'UserController@profilePic');
    Route::post('/profile/password', 'UserController@password');

    Route::prefix('configurations')->group(function () {
        Route::resource('/designation', 'Configurations\DesignationController');
        Route::resource('/department', 'Configurations\DepartmentController');
        Route::resource('/fiscalYear', 'Configurations\FiscalYearController');
        Route::get('/fiscalYear/status/{id}', 'Configurations\FiscalYearController@status');
        Route::resource('/country', 'Configurations\CountryController');
        Route::get('/country/status/{id}', 'Configurations\CountryController@status');
        Route::resource('/pradesh', 'Configurations\PradeshController');
        Route::resource('/muniType', 'Configurations\MuniTypeController');
        Route::resource('/district', 'Configurations\DistrictController');
        Route::resource('/municipality', 'Configurations\MunicipalityController');
        Route::resource('/officeType', 'Configurations\OfficeTypeController');

        Route::resource('/office', 'Configurations\OfficeController');
        Route::get('/office/status/{id}', 'Configurations\OfficeController@status');


    });

    Route::resource('/bodyWithdrawForm', 'Departed\BodyWithdrawFormController');



    Route::prefix('logs')->group(function () {
        Route::get('/loginLogs', 'LogController@loginLogs');
        Route::get('/failLoginLogs', 'LogController@failLogin');
    });

    Route::resource('feedback','FeedbackController');

});

app/SearchAndDeliver.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class SearchAndDeliver extends Model
{
    //
}

resources/views/backend/searchAndDeliver/index.blade.php
@extends('backend.layouts.app')
@section('content')

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                उद्दार तथा खोज तलासको निवेदन
                {{--<small>Menu</small>--}}
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"> Dashboard</a></li>
                <li class="active">उद्दार तथा खोज तलासको निवेदन</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            @include('backend.message.flash')
            <div class="row">
                @if(helperPermission()['isAdd'])
                    <div class="col-md-9" id="listing">
                        @else
                            <div class="col-md-12" id="listing">
                                @endif

                                <div class="box box-default">
                                    <div class="box-header with-border">
                                        <h3 class="box-title">उद्दार तथा खोज तलासको निवेदन</h3>
                                        <?php

                                        $permission = helperPermissionLink(url('user'), url('user'));

                                        $allowEdit = $permission['isEdit'];

                                        $allowDelete = $permission['isDelete'];

                                        $allowAdd = $permission['isAdd'];

                                        ?>
                                    </div>
                                    <div class="box-body">
                                        @if(!count($users)<=0)
                                            <div class="table-responsive">
                                                <table id="example1"
                                                       class="table table-striped table-bordered table-hover table-responsive">
                                                    <thead>
                                                    <tr>
                                                        <th>S.N</th>
                                                        <th>Name</th>
                                                        <th>Email</th>
                                                        <th>Designation</th>
                                                        <th class="text-center">Status</th>
                                                        <th style="width: 70px;" class="text-right">Action</th>
                                                    </tr>
                                                    </thead>

                                                    <tbody>
                                                    <?php
                                                    $i = 1;
                                                    ?>
                                                    @foreach($users as $user)
                                                        <tr>
                                                            <th scope=row>{{$i++}}</th>
                                                            <td>{{$user->name}}</td>
                                                            <td>{{$user->email}}</td>
                                                            <td>{{$user->designation->designation_name}}</td>
                                                            <td>
                                                                @if($user->id != \Illuminate\Support\Facades\Auth::user()->id)
                                                                    @if($user->user_status== 'active')

                                                                        <a class="label label-success stat"
                                                                           href="{{url('/user/status',$user->id)}}">
                                                                            <strong class="stat"> Active
                                                                            </strong>
                                                                        </a>

                                                                    @elseif($user->user_status== 'inactive')
                                                                        <a class="label label-danger stat"
                                                                           href="{{url('/user/status',$user->id)}}">
                                                                            <strong class="stat"> Inactive
                                                                            </strong>
                                                                        </a>
                                                                    @endif
                                                                @endif
                                                            </td>
                                                            <td class="text-right">
                                                                @if($allowEdit)
                                                                    <a href="{{route('user.edit',[$user->id])}}"
                                                                       class="text-info btn btn-xs btn-default"
                                                                       data-toggle="tooltip"
                                                                       data-placement="top" title="Edit">
                                                                        <i class="fa fa-pencil-square-o"></i>
                                                                    </a>&nbsp;
                                                                @endif

                                                                @if($user->id != \Illuminate\Support\Facades\Auth::user()->id)

                                                                    @if($allowDelete)
                                                                        {!! Form::open(['method' => 'DELETE', 'class'=>'inline', 'route'=>['user.destroy',
                                                                            $user->id]]) !!}
                                                                        <button type="submit"
                                                                                class="btn btn-danger btn-xs deleteButton actionIcon"
                                                                                data-toggle="tooltip"
                                                                                data-placement="top" title="Delete"
                                                                                onclick="javascript:return confirm('Are you sure you want to delete?');">
                                                                            <i class="fa fa-trash-o"></i>
                                                                        </button>
                                                                    @endif
                                                                    {!! Form::close() !!}
                                                                @endif
                                                            </td>
                                                        </tr>
                                                    @endforeach

                                                    </tbody>

                                                </table>
                                            </div>


                                        @else
                                            <div class="col-md-12">
                                                <label class="form-control label-danger">No records found</label>
                                            </div>
                                        @endif

                                    </div>

                                    <!-- /.box-body -->
                                </div>
                                <!-- /.box -->
                            </div>

                            @if($allowAdd)
                                <div class="col-md-3">
                                    @if(\Request::segment(3)=='edit')
                                        @include('backend.users.edit')
                                    @else
                                        @include('backend.users.add')
                                    @endif

                                </div>
                            @endif
                    </div>
            </div>
        </section>
        <!-- /.content -->
    </div>
@endsection